server:
  port: 8100

connection:
  list:
    file: "./connections.yaml"
  default:
    url: localhost:9999
    driver: FlaNium
    isLocal: true
    path: C:\FlaNium.Desktop.Driver-v1.6.0\FlaNium.Driver.exe

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/"