server:
  port: 8100
  servlet:
    context-path: /
  jetty:
    threads:
      acceptors: -1

connection:
  list:
    file: "./connections.yaml"
  default:
    url: 192.168.89.17:9999
    driver: FlaNium
    isLocal: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/"