connections:
  - testingOne:
      url: localhost:9999
      driver: Winium
  - testingTwo:
      url: localhost:8098
      driver: remoteEye
  - testingThree:
      url: localhost:9998
      driver: FlaNium
  - testingFour:
      url: localhost:8888
      driver: Winium2